- alias: Vanessa est partie
  id: vanessa_left
  hide_entity: true
  trigger:
    platform: state
    entity_id: device_tracker.vanessa
    to: not_home
    for:
      minutes: 5
  action:
    service: ifttt.trigger
    data:
      event: vanessa_leaves
- alias: Appartement Vide
  id: empty_flat
  hide_entity: true
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: not_home
  action:
  - data:
      entity_id: media_player.bureau,media_player.cuisine,media_player.salon
    service: media_player.media_pause
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_arm_away
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  - data:
      entity_id: group.all_lights
    service: homeassistant.turn_off
  - data:
      entity_id: switch.ganondorf_schedule
    service: switch.turn_on
  - data:
      entity_id: input_boolean.lumiere_entree_auto
    service: input_boolean.turn_on
- alias: Appartement occupé
  id: full_house
  hide_entity: true
  trigger:
  - entity_id: group.all_devices
    platform: state
    to: home
  action:
  - data:
      entity_id: switch.ganondorf_schedule
    service: switch.turn_off
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_disarm
  - data:
      entity_id: input_boolean.lumiere_entree_auto
    service: input_boolean.turn_off
- alias: Restart alarm if away
  hide_entity: true
  id: boot_away
  trigger:
  - event: start
    platform: homeassistant
  condition:
  - condition: state
    entity_id: group.all_devices
    state: not_home
  action:
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_arm_away
  - data:
      entity_id: input_boolean.lumiere_entree_auto
    service: input_boolean.turn_on
- alias: 'Rapport Activite Elsys #work'
  id: erp_elsys
  hide_entity: true
  trigger:
    platform: time
    at: '14:30:00'
  condition:
    condition: zone
    entity_id: device_tracker.hugo_iphone
    zone: zone.work
  action:
    service: notify.pushbullet
    data:
      message: Rapport Activité Elsys
      title: ERP
      data:
        url: https://portail.advans-group.com/ActivityReport
- alias: Batterie iPhone faible
  id: low_battery_iphone
  hide_entity: true
  trigger:
  - below: 30
    entity_id: sensor.battery_iphone
    platform: numeric_state
  - entity_id: device_tracker.hugo_iphone
    event: enter
    platform: zone
    zone: zone.work
  - entity_id: device_tracker.hugo_iphone
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: zone
        entity_id: device_tracker.hugo_iphone
        zone: zone.work
      - condition: zone
        entity_id: device_tracker.hugo_iphone
        zone: zone.home
    - below: 30
      condition: numeric_state
      entity_id: sensor.battery_iphone
  action:
  - data:
      message: Batterie iPhone < 30%, penser a recharger
      title: Batterie iPhone
    service: notify.pushbullet
- id: bed_time
  alias: Au Dodo
  trigger:
  - entity_id: light.lumieres_salon
    platform: state
    to: 'off'
  condition:
  - after: '22:00:00'
    before: 06:00:00
    condition: time
  action:
  - alias: Fermeture Volet
    data:
      entity_id: cover.tous_les_volets
    service: cover.close_cover
  - alias: Extinction TV
    data:
      entity_id: remote.harmony_hub
    service: remote.turn_off
  - data:
      entity_id: input_boolean.babyphone_chambre
    service: input_boolean.turn_on
- action:
  - alias: Allumer Arbre Lumière
    data:
      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    service: switch.turn_on
  - data:
      entity_id: switch.guirlande_noel
    service: switch.turn_on
  alias: Synchro Lumière Salon (ON)
  condition:
  - condition: state
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    state: 'off'
  id: on_arbre_lumière
  trigger:
  - entity_id: light.meuble_tv
    from: 'off'
    platform: state
    to: 'on'
- action:
  - delay: 00:00:10
  - alias: extinction Arbre lumière
    data:
      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    service: switch.turn_off
  - data:
      entity_id: switch.guirlande_noel
    service: switch.turn_off
  alias: Synchro Lumière Salon (OFF)
  condition:
  - condition: state
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    state: 'on'
  id: off_arbre_lumière
  trigger:
  - entity_id: light.meuble_tv
    from: 'on'
    platform: state
    to: 'off'
- action:
  - data:
      data:
        attachment:
          content-type: jpeg
        push:
          badge: 0
          category: camera
        entity_id: camera.salon
      message: Quelqu'un d'inconnu a été vu
    service: notify.iosapp
  alias: '[ALARME] [iOS] Notification pour déclencher alarme manuellement'
  condition:
  - condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: '''armed_away'''
  id: alarm_unknown
  trigger:
  - entity_id: binary_sensor.salon_someone_unknown
    platform: state
    to: 'on'
- action:
  - data:
      message: Test
    service: notify.iosapp
  alias: '[ALARME] [iOS] Alarme déclenché manuellement'
  condition: []
  id: alarm_manual_trigger
  trigger:
  - event_data:
      actionName: FIRE_ALARM
    event_type: ios.notification_action_fired
    platform: event
- action:
  - data:
      entity_id: alarm_control_panel.ha_alarm
    service: alarm_control_panel.alarm_disarm
  alias: '[ALARME] [iOS] Désactiver alarme manuellement'
  condition: []
  id: alarm_manual_disable
  trigger:
  - event_data:
      actionName: CANCEL_ALARM
    event_type: ios.notification_action_fired
    platform: event
- action:
  - data:
      entity_id: group.current_weather_day
      visible: 'False'
    service: group.set_visibility
  - data:
      entity_id: group.current_weather_night
      visible: 'True'
    service: group.set_visibility
  alias: Météo Nuit
  hide_entity: false
  condition:
    condition: or
    conditions:
    - before: sunrise
      before_offset: -03:00:00
      condition: sun
    - after: sunset
      after_offset: -03:00:00
      condition: sun
  id: '1504704434001'
  trigger:
  - event: sunset
    offset: -03:00:00
    platform: sun
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: group.current_weather_day
      visible: 'True'
    service: group.set_visibility
  - data:
      entity_id: group.current_weather_night
      visible: 'False'
    service: group.set_visibility
  alias: Météo Jour
  hide_entity: false
  condition:
    condition: and
    conditions:
    - before: sunset
      before_offset: -03:00:00
      condition: sun
    - after: sunrise
      after_offset: -03:00:00
      condition: sun
  id: meteo_jour
  trigger:
  - event: sunrise
    offset: -03:00:00
    platform: sun
  - event: start
    platform: homeassistant
- action:
  - service: sensor.update_speedtest
  - delay: 00:01:00
  - data: {}
    service: sensor.update_fastdotcom
  - data:
      entity_id: group.all_automations
    service: homeassistant.turn_on
  - service: google_assistant.request_sync
  trigger:
  - event: start
    platform: homeassistant
  alias: Boot
  id: boot
- id: '1504888310936'
  alias: Ouverture volet en journée (Salon)
  trigger:
  - entity_id: light.lumieres_salon
    from: 'off'
    platform: state
    to: 'on'
  - event: sunrise
    platform: sun
  condition:
  - condition: and
    conditions:
    - after: sunrise
      condition: sun
    - before: sunset
      condition: sun
    - condition: state
      entity_id: light.salon
      state: 'on'
  action:
  - before: '18:00:00'
    condition: time
  - data:
      entity_id: cover.volet_salon
    service: cover.stop_cover
- id: '1506437908730'
  alias: Lumière du jour suffisante dans salon
  trigger:
  - platform: template
    value_template: '{{ states.sensor.multisensor_entree_luminance.state | float >
      20 }}'
  condition:
  - condition: state
    entity_id: light.lumieres_salon
    state: 'on'
  action:
  - alias: Extinction lumière automatique
    data:
      entity_id: light.salon
    service: light.turn_off
- action:
  - alias: Lumière Bienvenue
    data:
      brightness: 254
      entity_id: light.spot_entree
      rgb_color:
      - 255
      - 195
      - 98
    service: light.turn_on
  - delay: 00:00:30
  - condition: state
    entity_id: group.all_devices
    state: not_home
  - data:
      entity_id: light.spot_entree
    service: light.turn_off
  alias: Lumière entrée - Bienvenue
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.lumiere_entree_auto
      state: 'on'
    - condition: template
      value_template: '{{ states(''sensor.multisensor_entree_luminance'') | float
        < 10  }}'
  id: '1507645975510'
  trigger:
  - entity_id: binary_sensor.multisensor_entree_sensor
    from: 'off'
    platform: state
    to: 'on'
