- platform: time_date
  display_options:
    - 'time'

- platform: uber
  server_token: !secret server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  product_ids:
    - 'f2ea021d-af59-4511-8dca-1c4a6cfc8f9b'

- platform: dnsip
- platform: dnsip
  hostname: dupras.fr

- platform: template
  sensors:
      bayesian_prob:
          friendly_name: Bayesian probability
          unit_of_measurement: '%'
          value_template: '{{ (states.binary_sensor.bayesian_sleeping.attributes.probability * 100) | round(0) }}'
