- platform: time_date
  display_options:
    - 'time'

- platform: uber
  server_token: !secret server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  product_ids:
    - 'f2ea021d-af59-4511-8dca-1c4a6cfc8f9b'

- platform: dnsip
- platform: dnsip
  hostname: dupras.fr

- platform: template
  entity_id:
    - sensor.netatmo_salon_temperature
    - sensor.netatmo_salon_temperature
  sensors:
      temp_moy_salon:
          friendly_name: Temperature moyenne
          unit_of_measurement: '°C'
          value_template: '{% if states.sensor.netatmo_salon_temperature.state and states.sensor.netatmo_salon_temperature.state != "unknown" %}
              {{ (((states.climate.salon.attributes.current_temperature | float) +
              (states.sensor.netatmo_salon_temperature.state | float)) / 2)|round(1) }}
          {%else%}
              {{ states.climate.salon.attributes.current_temperature}}
          {%endif%}'

