- platform: time_date
  display_options:
    - 'time'

- platform: uber
  server_token: !secret server_token
  start_latitude: !secret home_latitude
  start_longitude: !secret home_longitude
  product_ids:
    - 'f2ea021d-af59-4511-8dca-1c4a6cfc8f9b'

- platform: dnsip
- platform: dnsip
  hostname: dupras.fr

- platform: hue_sensors
- platform: template
  sensors:
      lux_hue_cuisine:
          friendly_name: Luminosité Cuisine (Hue Motion)
          unit_of_measurement: 'lux'
          value_template: '{{ float(10**((states.sensor.capteur_motion_cuisine.attributes.light_level-1)/10000)) | round(0) }}'
- platform: template
  sensors:
      temp_hue_cuisine:
          friendly_name: Température Cuisine (Hue Motion)
          unit_of_measurement: '°C'
          value_template: '{{ states.sensor.capteur_motion_cuisine.attributes.temperature| round(0) }}'
