climate.remotec_zxt120eu_unused_4:
  ignored: true
  polling_intensity: 0
climate.remotec_zxt120eu_unused_6:
  ignored: true
  polling_intensity: 0
sensor.remotec_zxt120eu_temperature:
  ignored: false
  polling_intensity: 0
sensor.fibaro_system_fgwpef_wall_plug_gen5_power:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.multisensor_entree_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpef_wall_plug_gen5_exporting:
  ignored: true
  polling_intensity: 0
binary_sensor.multisensor_entree_sensor:
  ignored: false
  polling_intensity: 60
sensor.detecteur_inondation_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.detecteur_inondation_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.detecteur_inondation_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.machine_a_laver_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.machine_a_laver_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.machine_a_laver_exporting:
  ignored: true
  polling_intensity: 0
sensor.machine_a_laver_sourcenodeid:
  ignored: true
  polling_intensity: 0
switch.machine_a_laver_switch:
  ignored: true
  polling_intensity: 0
binary_sensor.fibaro_system_fgdw002_door_opening_sensor_2_sensor:
  ignored: false
  polling_intensity: 1
