climate.remotec_zxt120eu_unused_4:
  ignored: true
  polling_intensity: 0
climate.remotec_zxt120eu_unused_6:
  ignored: true
  polling_intensity: 0
sensor.remotec_zxt120eu_temperature:
  ignored: false
  polling_intensity: 0
sensor.arbre_lumiere_power:
  ignored: true
  polling_intensity: 0
sensor.arbre_lumiere_alarm_level:
  ignored: false
  polling_intensity: 0
sensor.multisensor_entree_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.arbre_lumiere_exporting:
  ignored: true
  polling_intensity: 0
