climate.remotec_zxt120eu_unused_4:
  ignored: true
  polling_intensity: 0
climate.remotec_zxt120eu_unused_6:
  ignored: true
  polling_intensity: 0
sensor.remotec_zxt120eu_temperature:
  ignored: false
  polling_intensity: 2
sensor.fibaro_system_fgwpef_wall_plug_gen5_power:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_level:
  ignored: false
  polling_intensity: 0
sensor.aeotec_zw100_multisensor_6_sourcenodeid:
  ignored: true
  polling_intensity: 0
sensor.fibaro_system_fgwpef_wall_plug_gen5_exporting:
  ignored: true
  polling_intensity: 0
