### Chromecast/Harmony Sync ###
#- alias: "Chromecast => démarre ampli"
#  hide_entity: true
#  initial_state: 'on'
#  trigger:
#      platform: state
#      entity_id: media_player.salon_chromecast
#      from: 'off'
#  condition:
#      condition: time
#      after: '07:00:00'
#  action:
#      service: remote.turn_on
#      data:
#          activity: 'Regarder Chromecast'
#          entity_id: remote.harmony_hub

- alias: "Chromecast => stop ampli"
  hide_entity: true
  initial_state: 'on'
  trigger:
      platform: state
      entity_id: media_player.salon_chromecast
      to: 'off'
      for:
          minutes: 1
  condition:
      condition: template
      value_template: '{{ is_state("sensor.harmony_salon", "Regarder Chromecast") }}'
  action:
      service: remote.turn_off
      data:
          entity_id: remote.harmony_hub
