#Google Calendar
google:
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

tts:
  - platform: google
    language: 'fr'

sensor:
  - platform: google_travel_time
    name: Trajet Maison->Travail
    api_key: !secret google_api_key
    origin: zone.home
    destination: zone.work
    options:
        departure_time: now

  - platform: google_travel_time
    name: Trajet Travail->Maison
    api_key: !secret google_api_key
    origin: zone.work
    destination: zone.home
    options:
        departure_time: now

  - platform: google_travel_time
    name: Retour Maison
    api_key: !secret google_api_key
    origin: device_tracker.hugo_iphone
    destination: zone.home
    options:
        departure_time: now
