###############################################################################
# PACKAGE:      Harmony
# Description:
###############################################################################
remote:
    platform: harmony
    name: Harmony Hub
    activity: 'Regarder Apple TV'

sensor:
    platform: template
    sensors:
        harmony_salon:
            value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
            friendly_name: 'Harmony Salon'

group:
    harmony_hub:
        name: Harmony Hub
        icon: mdi:remote
        entities:
          - sensor.harmony_salon
          - remote.harmony_hub
          - input_boolean.appletv
          - input_boolean.ps4
          - input_boolean.switch
          - input_boolean.music
          - input_boolean.chromecast

#These inputs are mainly used as script flags
input_boolean:
    appletv:
        name: Regarder Apple TV
        icon: mdi:apple
    music:
        name: Écouter de la musique
        icon: mdi:music-circle
    ps4:
        name: Jouer à PS4
        icon: mdi:playstation
    switch:
        name: Jouer à la Switch
        icon: mdi:nintendo-switch
    chromecast:
        name: Regarder Chromecast
        icon: mdi:cast

input_select:
    harmony:
        name: Harmony Activities
        initial: PowerOff
        options:
          - Regarder Apple TV
          - Jouer à PS4
          - Jouer a la Switch
          - Écouter de la musique
          - Regarder Chromecast
          - PowerOff
###############################################################################
# Automations
###############################################################################
automation:
###############################################################################
# Global
###############################################################################
  - alias: Remote external update living room
    hide_entity: true
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.harmony
        option: '{{ states.remote.harmony_hub.attributes.current_activity }}'
  - alias: Remote start activity from input select living room tv
    hide_entity: true
    trigger:
      platform: state
      entity_id: input_select.harmony
    condition:
      condition: template
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity != states.input_select.harmony.state
        }}'
    action:
      service: remote.turn_on
      data_template:
        entity_id: remote.harmony_hub
        activity: '{{ states.input_select.harmony.state }}'

###############################################################################
# Apple TV
###############################################################################
  - alias: "Regarder Apple TV demarr\xE9 depuis Harmony"
    hide_entity: true
    trigger:
      platform: state
      entity_id: remote.harmony_hub
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.to_state.attributes.current_activity == "Regarder
          Apple TV" }}'
    action:
      - service: media_player.turn_on
        entity_id: media_player.apple_tv
  - alias: "Synchro AppleTV mediaplayer <=> Harmony au boot"
    hide_entity: true
    trigger:
        event: start
        platform: homeassistant
    condition:
        condition: template
        value_template: '{{ states.remote.harmony_hub.attributes.current_activity != "Regarder
          Apple TV" }}'
    action:
        service: media_player.turn_off
        entity_id: media_player.appletv
###############################################################################
# Sonos
###############################################################################

###############################################################################
# Chromecast
###############################################################################


###############################################################################
# Set states after restart
###############################################################################
  - alias: "Get Current Harmony state (appleTV)"
    hide_entity: true
    trigger:
        platform: homeassistant
        event: start
    condition:
        condition: template
        value_template: '{{ not is_state("sensor.harmony_salon", "PowerOff") }}'
    action:
        service: input_boolean.turn_on
        data_template:
            entity_id: >
              {% if is_state("sensor.harmony_salon", "Jouer à PS4") %}
                  input_boolean.ps4
              {% elif is_state("sensor.harmony_salon", "Regarder Apple TV") %}
                  input_boolean.appletv
              {% elif is_state("sensor.harmony_salon", "Écouter de la musique") %}
                  input_boolean.music
              {% elif is_state("sensor.harmony_salon", "Jouer a la Switch") %}
                  input_boolean.switch
              {% endif %}

  - alias: Harmony Set Input Select On Start
    hide_entity: true
    trigger:
        platform: homeassistant
        event: start
    action:
      - delay:
          seconds: 30
      - service: input_select.select_option
        data_template:
            entity_id: input_select.harmony
            option: '{{ states.remote.salon.attributes.current_activity }}'
