homekit:
    auto_start: False
    filter:
        include_entities:
          - device_tracker.hugo_iphone
          - device_tracker.vanessa
        exclude_domains:
          - device_tracker
          - light
          - script
          - remote
          - sensor
          - binary_sensor
          - automation
        exclude_entities:
          - switch.ganondorf_schedule
          - switch.machine_a_laver
          - input_boolean.babyphone
          - input_boolean.guest_mode
          - input_boolean.neato_weekend
          - input_boolean.lumiere_entree_auto
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch_2
    entity_config:
        switch.fibaro_system_fgwpef_wall_plug_gen5_switch:
            name: Boule de Lumière
        switch.fibaro_system_fgwpef_wall_plug_gen5_switch_2:
            name: Arbre de Lumière

automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: 00:05  # Waits 5 minutes
      - service: homekit.start
