light:
  - platform: hue
    scan_interval: 10
  - platform: group
    name: Spots Salon
    entities:
      - light.spot_bibliotheque
      - light.spot_entree
      - light.spot_salon
      - light.spot_salon_couloir
  - platform: group
    name: Spots Couloir
    entities:
      - light.spot_couloir_1
      - light.spot_couloir_2

sensor:
  - platform: hue
    ip_address: !secret hue_ip_address
    token: !secret hue_token

group:
    lumiere_piece:
        name: Lumière Pièces
        control: hidden
        entities:
          - light.salon
          - light.couloir
          - light.parents__chambre
          - light.ianto__chambre
          - light.zelda__chambre
          - light.terrasse

    spots_salon:
        name: Spots Salon
        entities:
          - light.spot_bibliotheque
          - light.spot_entree
          - light.spot_salon
          - light.spot_salon_couloir

    lumiere_couloir:
        name: Spots Couloir
        entities:
          - light.spot_couloir_1
          - light.spot_couloir_2

    lumieres_chambre:
        name: Lumières Chambre
        entities:
          - light.plafond_chambre
          - light.lampe_de_chevet_hugo
          - light.lampe_de_chevet_vanessa

    lumiere_chambre_enfant:
        name: Lumière Chambre Enfant
        entities:
          - light.plafond_chambre_enfant
          - light.lampe_chevet_ianto

    lumiere_chambre_ami:
        name: Lumière Chambre Ami
        entities:
          - light.lampe_chambre_damis
          - light.hue_ambiance_candle_1

    scene_hue:
        name: Scène Hue
        control: hidden
        entities:
          - script.hue_soiree_tv
          - script.hue_veilleuse_hugo

script:
    hue_soiree_tv:
        alias: Scène soirée TV
        sequence:
          - service: hue.hue_activate_scene
            data:
                group_name: "Salon"
                scene_name: "Détente"
    hue_veilleuse_hugo:
        alias: Scène Veilleuse Hugo
        sequence:
          - service: hue.hue_activate_scene
            data:
                group_name: "Chambre"
                scene_name: "Détente"
    hue_debut_soiree:
        alias: Début de soirée
        sequence:
          - service: hue.hue_activate_scene
            data:
                group_name: "Salon"
                scene_name: "Lecture"

switch:
  - platform: flux
    start_time: '07:00'
    stop_time: '21:00'
    lights:
      - light.spot_bibliotheque
      - light.spot_entree
      - light.spot_salon
      - light.spot_salon_couloir
      - light.plafonnier_salon
      - light.lampe_du_cube
      - light.hue_go
    mode: xy

  - platform: flux
    name: "Flux Meuble TV"
    start_time: '07:00'
    stop_time: '21:00'
    lights:
      - light.meuble_tv
    mode: rgb
    brightness: 128
