###############################################################################
# PACKAGE:      meteo
###############################################################################
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    lang: FR
    monitored_conditions:
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_1d_kph
      - alerts

  - platform: yr
    monitored_conditions:
      - symbol

weather:
  - platform: yweather

group:
    daily_forecast:
        name: Prévision météo
        entities:
          - sensor.pws_weather_2d_metric
          - sensor.pws_weather_2n_metric
          - sensor.pws_weather_3d_metric
          - sensor.pws_weather_3n_metric
          - sensor.pws_weather_4d_metric
          - sensor.pws_weather_4n_metric

    weather_overview:
        name: Météo
        entities:
          - sensor.pws_weather_1d_metric
          - sensor.waqi_nice_aeroport_paca_france
          - sensor.pws_temp_high_record_c
          - sensor.pws_temp_high_1d_c
          - sensor.pws_temp_c
          - sensor.pws_temp_low_1d_c
          - sensor.pws_temp_low_record_c
          - sensor.pws_precip_1d
          - sensor.pws_precip_1d_mm
          - sensor.pws_wind_kph
          - sensor.pws_wind_1d_kph
          - sensor.pws_alerts
          - sensor.pws_weather_1n_metric
