###############################################################################
# PACKAGE:      Netatmo
# Description:  netatmo sensor requires username, password.
###############################################################################

homeassistant:
    customize:
        sensor.netatmo_chambre_battery:
            hidden: true
        sensor.netatmo_chambre_radio:
            hidden: true
        sensor.netatmo_chambre_enfant_battery:
            hidden: true
        sensor.netatmo_chambre_enfant_radio:
            hidden: true
        sensor.netatmo_exterieur_battery:
            hidden: true
        sensor.netatmo_exterieur_radio:
            hidden: true
        sensor.netatmo_station_wifi:
            hidden: true

#Netatmo Component
netatmo:
    api_key: !secret netatmo_api_key
    secret_key: !secret netatmo_secret_key
    username: !secret netatmo_username
    password: !secret netatmo_password

group:
    netatmo_salon:
        name: Netatmo Salon
        entities:
          - sensor.netatmo_station_temperature
          - sensor.netatmo_station_co2
          - sensor.netatmo_station_humidity
          - sensor.netatmo_station_noise
    
    netatmo_exterieur:
        name: Netatmo Extérieur
        entities:
          - sensor.netatmo_exterieur_temperature
          - sensor.netatmo_exterieur_humidity
          - sensor.netatmo_station_pressure
    
    netatmo_chambre:
        name: Netatmo Chambre
        entities:
          - sensor.netatmo_chambre_temperature
          - sensor.netatmo_chambre_co2
          - sensor.netatmo_chambre_humidity

    netatmo_chambre_enfant:
        name: Netatmo Chambre Enfant
        entities:
          - sensor.netatmo_chambre_enfant_temperature
          - sensor.netatmo_chambre_enfant_co2
          - sensor.netatmo_chambre_enfant_humidity

    welcome_salon_binary_sensors:
        name: Netatmo Welcome
        entities:
          - binary_sensor.salon_motion
          - binary_sensor.salon_someone_known
          - binary_sensor.salon_someone_unknown