homeassistant:
    customize:
        sensor.nut_ups_status_data:
            hidden: true
        sensor.nut_ups_battery_runtime:
            hidden: true
        sensor.ups_battery_runtime_min:
            icon: mdi:timer

sensor:
  - platform: nut
    host: 192.168.1.20
    username: admin
    password: 1111
    resources:
        - ups.status
        - ups.load
        - input.voltage
        - battery.runtime
        - battery.charge
        - ups.beeper.status
        - ups.model
  
  - platform: template
    entity_id: sensor.nut_ups_status_data
    sensors:
      ups_status:
        friendly_name: UPS Status
        value_template: >-
          {%- if is_state('sensor.nut_ups_status_data', 'OL') %}
            Normal
          {% elif is_state('sensor.nut_ups_status_data', 'OL CHRG') %}
            En Charge
          {% elif is_state('sensor.nut_ups_status_data', 'OB DISCHRG') %}
            Batterie
          {% elif is_state('sensor.nut_ups_status_data', 'LB DISCHRG') %}
            Batterie Faible
          {% elif is_state('sensor.nut_ups_status_data', 'RB') %}
            Remplacer Batterie
          {% else %}
            Inconnu
          {%- endif %}
          
  - platform: template
    entity_id: sensor.nut_ups_battery_runtime
    sensors:
      ups_battery_runtime_min:
        friendly_name: NUT UPS Battery Runtime
        unit_of_measurement: 'min'
        value_template: '{{ (float(states.sensor.nut_ups_battery_runtime.state) / 60) | round(0)  }}'

binary_sensor:
  - platform: template
    entity_id: sensor.nut_ups_status_data
    sensors:
      ups_status_bs:
        friendly_name: UPS
        device_class: light
        value_template: "{{ states.sensor.nut_ups_status_data.state == 'OL' or states.sensor.nut_ups_status_data.state == 'OL CHRG' }}"

group:
    apc_ups:
        name: Onduleur
        entities:
          - sensor.nut_ups_model
          - binary_sensor.ups_status_bs
          - sensor.ups_status
          - sensor.nut_ups_battery_charge
          - sensor.nut_ups_load
          - sensor.ups_battery_runtime_min
          - sensor.nut_ups_input_voltage
          - sensor.nut_ups_beeper_status