sensor:
  - platform: systemmonitor
    resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
    - type: swap_use

group:
    System:
        name: System
        entities:
          - sensor.processor_use
          - sensor.disk_use_percent_
          - sensor.memory_free
          - sensor.swap_use
          - sensor.last_boot
