homeassistant:
    customize:
        cover.volet_salon:
            homebridge_cover_type: rollershutter
        cover.volet_chambre_amis:
            homebridge_cover_type: rollershutter
        cover.volet_cuisine:
            homebridge_cover_type: rollershutter
        cover.global_cover:
            homebridge_hidden: true

cover:
  - platform: template
    covers:
        global_cover:
            friendly_name: "Commande volet generale"
            position_template: "50"
            open_cover:
                service: script.ouvrir_volet
            close_cover:
                service: script.fermer_volet
            stop_cover:
                service: script.volet_stop

script:
    ouvrir_volet:
        alias: Ouverture Volet
        sequence:
          - service: cover.open_cover
            entity_id: cover.volet_salon
          - service: cover.open_cover
            entity_id: cover.volet_chambre_amis
          - service: cover.open_cover
            entity_id: cover.volet_cuisine
    fermer_volet:
        alias: Fermeture Volet
        sequence:
          - service: cover.close_cover
            entity_id: cover.volet_salon
          - service: cover.close_cover
            entity_id: cover.volet_chambre_amis
          - service: cover.close_cover
            entity_id: cover.volet_cuisine
    volet_stop:
        alias: Arret Volet/MyPosition
        sequence:
          - service: cover.stop_cover
            entity_id: cover.volet_salon
          - service: cover.stop_cover
            entity_id: cover.volet_chambre_amis
          - service: cover.stop_cover
            entity_id: cover.volet_cuisine
