homeassistant:
    customize:
        binary_sensor.multisensor_entree_sensor:
            device_class: motion
        sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_level:
            hidden: true
        sensor.fibaro_system_fgwpef_wall_plug_gen5_alarm_type:
            hidden: true
        sensor.fibaro_system_fgwpef_wall_plug_gen5_exporting:
            hidden: true
        sensor.fibaro_system_fgwpef_wall_plug_gen5_power_2:
            hidden: true
        sensor.fibaro_system_fgwpef_wall_plug_gen5_power_management:
            hidden: true
        sensor.fibaro_system_fgwpef_wall_plug_gen5_sourcenodeid:
            hidden: true
        sensor.multisensor_entree_alarm_level:
            hidden: true
        sensor.multisensor_entree_alarm_type:
            hidden: true
        sensor.multisensor_entree_sourcenodeid:
            hidden: true
        climate.remotec_zxt120eu_heating_1:
            hidden: false
        climate.remotec_zxt120eu_unused_4:
            hidden: true
        climate.remotec_zxt120eu_unused_6:
            hidden: true

zwave:
    usb_path: /dev/ttyACM0

climate:
  - platform: zwave

group:
    zw_multisensor_entree:
        name: Multisensor Entrée
        entities:
          - binary_sensor.multisensor_entree_sensor
          - sensor.multisensor_entree_temperature
          - sensor.multisensor_entree_relative_humidity
          - sensor.multisensor_entree_luminance
          - sensor.multisensor_entree_ultraviolet
          - sensor.multisensor_entree_burglar
    zw_fibaro_system_fgwpef_wall_plug_gen5:
        name: Arbre Lumière
        entities:
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
    zw_detecteur_inondation:
        name: Détecteur Inondation
        entities:
          - binary_sensor.detecteur_inondation_sensor
          - sensor.detecteur_inondation_temperature
          - sensor.detecteur_inondation_flood
          - sensor.detecteur_inondation_flood_2
          - sensor.detecteur_inondation_general
          - sensor.detecteur_inondation_burglar
    zw_prise_machine_laver:
        name: Machine à Laver
        entities:
          - switch.machine_a_laver_switch
          - sensor.machine_a_laver_energy
          - sensor.machine_a_laver_power